PracticaAlmacenes/Controllers/AlmacenController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PracticaAlmacenes.Filtros;
using PracticaAlmacenes.Models;

namespace PracticaAlmacenes.Controllers
{
    public class AlmacenController : Controller
    {
        mitienda02Entities1 db=  new mitienda02Entities1();

        public ActionResult Borrar(int id)
        {
            var data = db.Almacen.Find(id);
            //si tienes un producto ALmacen pues eliminamelos. Esto es un borrado en casacada. 
            //No se suele utilizar este metodo.
            if (data.ProductosAlmacen.Any()) db.ProductosAlmacen.RemoveRange(data.ProductosAlmacen);
            {
                db.Almacen.Remove(data);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        //listado de almacenes accedemos y la pasamos a la vista
        public ActionResult Index()
        {
            var data = db.Almacen;
            return View(data);
        }

        [FiltroId]
        public ActionResult Modificacion(int id)
        {
            var data = db.Almacen.Find(id);
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Modificacion(Almacen model)
        {
            if (ModelState.IsValid)
            {
                //este modelo modificado en model esta el id
                db.Entry(model).State=EntityState.Modified;
                db.SaveChanges();
                //cuando llegue aqui, vuelve a index
                return RedirectToAction("Index");
            }

            return View(model);
        }

        //public ActionResult Detalle(int id)
        //{
        //    var data = db.Almacen.Find(id);
        //    return View(data);
        //}
        
        public ActionResult Alta()
        {
            return View(new Almacen());
        }
        
        [HttpPost]

        public ActionResult Alta(Almacen model)
        {
            if (ModelState.IsValid)
            {
                db.Almacen.Add(model);
                db.SaveChanges();
                return View(new Almacen());
                
            }
            return View(model);



        }

    }
}

PracticaAlmacenes/Views/Shared/_Layout.cshtml
@using System
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>



    @RenderSection("MiJavaScript", false)
</body>
</html>

PracticaAlmacenes/Views/Shared/_fichaAlmacen.cshtml
@model PracticaAlmacenes.Models.Almacen
    
<div class="col-md-3">
    <h3>@Html.DisplayFor(o => Model.nombre) </h3>
    <p>
        @Html.DisplayFor(o => Model.ciudad)
        @Html.DisplayFor(o => Model.codigo_postal)
    </p>
    <p>
        @Html.ActionLink("Modificar", "Modificacion", "Almacen",
                     new { id = Model.idAlmacen }, null
                    )

        <a href="#" class="borrame" data-id="@Model.idAlmacen">
            Borrar
        </a>

    </p>
</div>